name: C/C++ CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ConorMacBride/install-package@v1
      with:
        apt: libgtest-dev strace
    - uses: actions/checkout@v3
    - name: autoconf
      run: autoreconf -fi
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Archive testing logs
      if: '!cancelled()'
      uses: actions/upload-artifact@v3
      with:
        name: gtest-logs
        path: '**/*.log'
        retention-days: 1
